### ISSUE TITLE
[Windows 10] Unable to start appium server

### ISSUE THREAD

**Issue by bilalikram94** [prashant1507/Appium-Automation-Framework#1]
INFO: All devices are busy. Available device(s) 0.

java.lang.ThreadDeath
	at java.base/java.lang.Thread.stop(Thread.java:942)
	at org.automation.appium.AppiumSetup.getCapability(AppiumSetup.java:136)
	at org.automation.appium.AppiumSetup.startAppiumServer(AppiumSetup.java:44)
	at org.automation.driver.Driver.initDriver(Driver.java:43)
	at org.automation.tests.BaseSetup.setUp(BaseSetup.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

Jan 14, 2022 12:19:35 PM org.automation.utils.ShellCommandExecutor executeCommand
SEVERE: Failed to execute [ D:\02-Confidential and Critical Information\Bilal_Automation_personal\Appium-Automation-Framework-main/src/test/resources/adb/windows/adb.exe start-server ]. Failed to create capability file(s).

Process finished with exit code 1

**Comment by prashant1507** [comment]
can you please run 'appium-doctor' command and share the result

**Comment by bilalikram94** [comment]
no need was a environment issue resolved that and worked like a charm really impressed by the the way that you have built the framework, Everything is organized and very well built but I do need to know how to setup my log4j that is the only remaining issue i cant seem to solve :p

**Comment by prashant1507** [comment]
Thank You 

For Log4j - put a log4j.properties file in java/main/resources (Refer https://www.javatpoint.com/log4j-properties to check properties options)
add apache-log4j dependency in maven - https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core (use lates version as the older one has Vulnerabilities which cannot be ignored)

you may check this as well - https://howtodoinjava.com/log4j2/log4j2-properties-example/

**Comment by prashant1507** [comment]
closing the issue as cannot reproduce
